version: '3.3'

services:

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-frontend:latest
    restart: always
    container_name: sausage-frontend
    ports:
      - '80:80'
      - '8080:8080'

  backend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend:latest
    restart: always
    container_name: sausage-backend
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_VAULT_HOST

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report:latest
    restart: always
    container_name: sausage-backend-report
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_VAULT_HOST
