version: '3.7'

services:
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-frontend:latest
    restart: always
    container_name: sausage-frontend
    environment:
      DEFAULT_HOST: sausage-backend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - '80:80'
      - '443:443'

  green:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend:latest
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 6
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-backend
      VIRTUAL_PORT: 8080

  blue:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend:latest
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 6
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-backend
      VIRTUAL_PORT: 8080

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report:latest
    restart: always
    container_name: sausage-backend-report
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST

