version: '3.3'

services:

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-frontend:latest
    restart: always
    container_name: sausage-frontend
    environment:
      DEFAULT_HOST: sausage-backend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
    ports:
      - '80:80'

  backend:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend:latest
    restart: always
    environment:
      SPRING_CLOUD_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
      SPRING_CLOUD_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: sausage-backend

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report:latest
    restart: always
    container_name: sausage-backend-report
    environment:
      SPRING_VAULT_TOKEN: $SPRING_CLOUD_VAULT_TOKEN
      SPRING_VAULT_HOST: $SPRING_CLOUD_VAULT_HOST
